### ISSUE TITLE
Добавить контент на сайт

### ISSUE THREAD

**Issue by mgk-it** [mgk-it/cniip_minstroy#1]
- [x] В подразделе "ЗАКОНОДАТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ В СФЕРЕ ПРОТИВОДЕЙСТВИЯ КОРРУПЦИИ" раздела "Противодействие коррупции" после меню "Ведомственные нормативные правовые акты" добавить меню "Приказы учреждения", в которое и разместить все копии приказов, присланных мною.

- [x] Из меню "Ведомственные нормативные правовые акты" удалить ссылку "Приказ ФГБУ "ЦНИИП Минстроя России" № 128 от 10 декабря 2015 года «Об утверждении состава комиссии по противодействию коррупции в ФГБУ «ЦНИИП Минстроя России»" (приказ учреждения не является ведомственным, да и к тому же нормативным правовым актом).

**Comment by mgk-it** [comment]
Виталий, предлагаю построить работу так. 
Здесь создаем задания.
Сигналом о том, что задача выполнена будет проставленная галочка. Вы со своей стороны проверяете и если все ок, закрываете issue кнопкой: Close and comment.

**Comment by BVG73** [comment]
Хорошо, давай попробуем.
