### ISSUE TITLE
Нужны данные

### ISSUE THREAD

**Issue by mgk-it** [mgk-it/cniip_minstroy#16]
Виталий, для раздела "КОМИССИЯ ПО СОБЛЮДЕНИЮ ТРЕБОВАНИЙ К СЛУЖЕБНОМУ ПОВЕДЕНИЮ И УРЕГУЛИРОВАНИЮ КОНФЛИКТА ИНТЕРЕСОВ" необходимы документы:
- [x] "Положение о комиссии ФГБУ ЦНИПП Минстроя России"
- [x] "Состав комиссии"

Для раздела "Противодействие коррупции"
- [x] Адрес e-mail для заявок с формы обратной связи

**Comment by BVG73** [comment]
Для раздела "Противодействие коррупции"
Адрес e-mail для заявок с формы обратной связи: otdel_kadrov@cniipminstroy.ru

**Comment by BVG73** [comment]
Состав и Положение о комиссии ФГБУ "ЦНИИП Минстроя России".
[Приказ №12 от 19.04.2016.pdf](https://github.com/mgk-it/cniip_minstroy/files/873026/12.19.04.2016.pdf)
