### ISSUE TITLE
Редактирование контента на сайте. Март 2017 г.

### ISSUE THREAD

**Issue by mgk-it** [mgk-it/cniip_minstroy#2]
**Расшифровка обозначений (X1-X2-Х3):**
X1 - номер пункта работ по договору ([список работ по договору](https://github.com/mgk-it/cniip_minstroy/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82-%D0%BF%D0%BE-%D0%B4%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D1%83.-%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82%D0%B0))
X2 - количество внесенных изменений на сайт
X3 - максимальное количество изменений за отчетный месяц

**Изменения:**
- (4-1-20). Добавлен 1 раскрывающий список. 10.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/1)
- (3-6-20). Добавлено 5 ссылок на файлы, удалена 1 ссылка на файл. 10.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/1)
- (3-7-20). Обновлен текст на странице. 17.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/3)
- (7-1-10). Изменение очередности следования фотографий руководства. 20.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/6)
- (7-2-10). Сделать возможность размещения 3-х новостей в блоке "На повестке дня". 20.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/5) п.2
- (3-9-20). Замена 2 фотографий руководства. 20.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/8), [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/9)
- (3-10-20). Замена партнера. 21.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/8)
- (3-11-20). Добавлен сотрудник в раздел Руководство. 21.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/7)
- (3-14-20). Добавлено 3 документа в раздел Продиводействие коррупции. 21.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/4)
- (3-15-20). Добавлен партнер. 22.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/12)
- (3-17-20). Замена 2 фотографий руководства. 22.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/11), [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/10)
- (3-18-20). Обновлен текст  описания Гутникова В.А. 26.03.2017 г.[Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/15)
- (3-19-20). Обновлено название партнера 26.03.2017 г. [Посмотреть issue](https://github.com/mgk-it/cniip_minstroy/issues/14)

**Comment by BVG73** [comment]
По-моему, наименование надо изменить на "Работы по изменению контента на сайте. Февраль 2017 г. to Редактирование контента на сайте. Март 2017 г."

Эту задачу не закрываем до конца марта?

**Comment by BVG73** [comment]
сорри, название задачи надо сделать "Редактирование контента на сайте. Март 2017 г."

**Comment by mgk-it** [comment]
Этот issue для нас
