### ISSUE TITLE
Изменение очередности следования фотографий руководства

### ISSUE THREAD

**Issue by BVG73** [mgk-it/cniip_minstroy#6]
- [x] Необходимо изменить очередность следования фотографий руководства в подразделе "Руководство" раздела "Об Институте" в следующей последовательности:
1. Чабдаров Марат Мухажирович - генеральный директор;
2. Кривов Александр Сергеевич - научный руководитель проектных работ;
3. Маскулов Рамзит Мунирович - заместитель генерального директора по развитию;
4. Гутников Владимир Анатольевич - заместитель генерального директора по научной и учебной работе;
5. Солошенков Олег Владимирович - заместитель генерального директора по взаимодействию с органами государственной власти;
6. Монова Светлана Александровна - заместитель генерального директора по финансам.

Необходимо, чтобы данная последовательность соблюдалась при просмотре указанного выше подраздела на экране смартфонов.

**Comment by gazooz** [comment]
Нужна фотография Гутникова Владимира Анатольевича

**Comment by BVG73** [comment]
Во вложении фотография В.А. Гутникова. Прошу разместить на сайте.

![3](https://cloud.githubusercontent.com/assets/26256860/24092862/0d046db0-0d62-11e7-85f1-21d3a1101ba4.jpg)
